#!/bin/sh

rm ./bib/texput.log
rm ./images/proposedArchitecture.log
rm ./images/gan.glg
rm ./images/gan.gls
rm ./images/proposedArchitecture.glo
rm ./images/proposedArchitecture.aux
rm ./images/proposedArchitecture.synctex.gz
rm ./images/gan.ist
rm ./images/gan.glo
rm ./images/gan.log
rm ./images/gan.synctex.gz
rm ./images/gan.aux
rm ./main/main.glo
rm ./main/main.log
rm ./main/main.blg
rm ./main/main.toc
rm ./main/main.bbl
rm ./main/main.glg
rm ./main/main.aux
rm ./main/main.synctex.gz
rm ./main/main.gls
rm ./main/main.lof
rm ./main/main.glsdefs
rm ./main/main.lot
rm ./main/main.nlo
rm ./main/preamble.sty
rm ./main/main.ist
rm ./main/main.out
rm ./presentation/presentation.log
rm ./presentation/presentation.synctex.gz
rm ./presentation/presentation.aux
rm ./presentation/presentation.toc
rm ./presentation/presentation.pdfpc
rm ./presentation/presentation.nav
rm ./presentation/presentation.snm
rm ./presentation/presentation.blg
rm ./presentation/presentation.bbl
rm ./presentation/presentation.out
rm ./sections/Statement.glg
rm ./sections/Statement.aux
rm ./sections/significance.synctex.gz
rm ./sections/significance.gls
rm ./sections/significance.glo
rm ./sections/Statement.gls
rm ./sections/Statement.synctex.gz
rm ./sections/significance.log
rm ./sections/significance.ist
rm ./sections/Statement.ist
rm ./sections/Statement.glo
rm ./sections/Statement.log
rm ./sections/significance.aux
rm ./sections/significance.glg
